name: Build BetterMeowbit Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up ARM GCC
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '10.3-2021.10'

    - name: Make clean
      run: make clean

    - name: Build firmware
      run: make

    - name: Convert BIN to UF2
      run: python3 tools/uf2conv.py -c build/bettermeowbit.bin -o build/bettermeowbit.uf2

    - name: Upload UF2 firmware
      uses: actions/upload-artifact@v4
      with:
        name: bettermeowbit.uf2
        path: build/bettermeowbit.uf2
